version: '2'
services:
  shopfront:
    image: localhost:5000/shopfront
    ports:
      - "8010:8010"
    links:
      - productcatalogue
      - stockmanager
  productcatalogue:
    image: localhost:5000/productcatalogue
    ports:
      - "8020:8020"
  stockmanager:
    image: localhost:5000/stockmanager
    ports:
      - "8030:8030"
